export const CHANGE_FILTER_ADULTS = 'CHANGE_FILTER_ADULTS';
export const CHANGE_FILTER_CHILDREN = 'CHANGE_FILTER_CHILDREN';
export const CHANGE_FILTER_ROOMS = 'CHANGE_FILTER_ROOMS';
export const CHANGE_DISTINATION = 'CHANGE_DISTINATION';
export const CHANGE_SLIDER_DATA = 'CHANGE_SLIDER_DATA';
